### PR TITLE
Setting page improvement with widgets

### PR DESCRIPTION
**Pull request by teoh4770**

### CODE REVIEW

**Comment by juancwu** [comment]
I can see that you added the UserSettingForm to ask for the first and last name but I was thinking of adding a first name and last name field as well in the register form to have the information ready when the user register instead of having to update the information later on in the settings page.

**Comment by teoh4770** [comment]
Yeah let me add that real quick later

**Comment by teoh4770** [comment]
Yeah, I have made some changes according to what Juan suggests 👍

**Comment by teoh4770** [comment]
Screenshot 2022-05-19 at 5 10 40 PM

**Review by juancwu — APPROVED** [review]

**Review by AleksandarNe11 — APPROVED** [review]

**Comment by teoh4770** [comment]
Yeah I should add them both at the register page and setting page :0

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Pull request merged**
